# Generated by Django 6.0 on 2025-12-04 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя исполнителя')),
                ('bio', models.CharField(max_length=100, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название жанра')),
                ('discription', models.TextField(verbose_name='Описание жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='Имя')),
                ('email', models.CharField(max_length=50, verbose_name='Почта')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название Альбома')),
                ('release_date', models.DateField(verbose_name='Дата выхода альбома')),
                ('artist_id', models.ManyToManyField(to='sousyi.artist', verbose_name='Исполнители')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sousyi.genre')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название трека')),
                ('duration', models.IntegerField(verbose_name='Длительность (в секундах)')),
                ('album_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sousyi.album')),
                ('artist_id', models.ManyToManyField(to='sousyi.artist')),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sousyi.genre')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название плейлиста')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Время создания')),
                ('tracks', models.ManyToManyField(to='sousyi.track')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sousyi.user')),
            ],
            options={
                'verbose_name': 'Плейлист',
                'verbose_name_plural': 'Плейлисты',
            },
        ),
    ]
